### ISSUE TITLE
error on chrome

### ISSUE THREAD

**Issue by darktweek** [Merlintor/cisco-final-cheat#2]
Hi

I try the extension, but there some error in the extension pannel:

First:
Unrecognized manifest key 'applications'.
`
  "name": "Adblock Plus",
  "version": "1.0",
  "description": "The most popular ad blocker on Firefox, Chrome, Safari, Android and iOS",
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "adblock@merlin.gg"
    }
  },`

Second:
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
`{
  "name": "Adblock Plus",
  "version": "1.0",
  "description": "The most popular ad blocker on Firefox, Chrome, Safari, Android and iOS",
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "adblock@merlin.gg"
    }
`
![Capture d’écran du 2023-11-22 11-00-02](https://github.com/merlinfuchs/ccna-extension/assets/12700953/709cdde1-cf86-400f-bc82-e0001846141c)
![Capture d’écran du 2023-11-22 11-00-51](https://github.com/merlinfuchs/ccna-extension/assets/12700953/f41457d4-1802-44fd-b0a6-adb99871c6e0)

Can I correct it my self or can you do it ? 
Thnks

**Comment by merlinfuchs** [comment]
Hey, this extensions isn't maintained and I'm not even sure if it still works at all. I'm happy to accept a PR to update it to manifest version 3 tho!

**Comment by darktweek** [comment]
OK No I don't have the dev skills to make the modification.

**Comment by snoweuph** [comment]
@darktweek  I did rewrite this as a userscript, and it worked for me so far:
https://git.euph.dev/Snoweuph/CCNA_Autofill_Userscript

Moin @merlinfuchs , wir müssen jz auch den CCNA machen, nochmal danke für deinen code xD

**Comment by merlinfuchs** [comment]
@snoweuph Thanks for linking your alternative here, happy my code worked as an inspiration :)
I have added a link to yours to the README!
